### ISSUE TITLE
Webapp not loading

### ISSUE THREAD

**Issue by eleanormurray** [GerkeLab/ShinyDAG#27]
I'm getting the following error message when I try to open the webapp link:

![Screenshot_2021-09-28 An error has occurred](https://user-images.githubusercontent.com/16530545/135170137-5b36fe54-24d1-408b-adcd-05fc50dd46ed.png)

**Comment by tgerke** [comment]
Back up now (server had run out of storage for an unrelated reason), thanks @eleanormurray for letting us know!
